### PR TITLE
✅  New decimal-aware price system - Part 6: Fix auction tests

### PR DESCRIPTION
**Pull request by JuaniRios**
Main info on #260 

- This PR focuses on fixing the auction tests

### CODE REVIEW

**Comment by JuaniRios** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/266?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#266** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/266?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#265** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/265?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#264** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/264?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#263** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/263?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#262** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/262?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#260** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/260?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @JuaniRios and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by vstam1 — COMMENTED** [review]
Would be nice if we could create a seperate PR that reorders the imports, const, types and structs in each file in the funding pallet.

**Review by vstam1 — APPROVED** [review]
Lgtm

**Comment by JuaniRios** [comment]
### Merge activity

* **Apr 30, 9:52 AM EDT**: @JuaniRios started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Polimec/polimec-node/266).

**Pull request merged**
