### PR TITLE
🧪 Experiment hrmp weighing

### PR DESCRIPTION
**Pull request by JuaniRios**
## What?
- Write hrmp functions benchmarks

## Why?
- They are being called by the xcm executor, so are assigned a fixed weight. We need to make sure we are not going over that

## Anything Else?
Next PR will run these benches

### CODE REVIEW

**Comment by JuaniRios** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/351?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#351** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/351?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#346** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/346?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#345** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/345?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#341** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/341?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#344** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/344?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @JuaniRios and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by vstam1 — COMMENTED** [review]
How are you actually going to assign these weights? Or will you just run the weights and hardcode them in the XCM weights config?

**Comment by JuaniRios** [comment]
@vstam1 We are not going to use these weights for now. The struct that computes the XCM weight `FixedWeightBounds` assigns the same fixed weight to all instructions except `Transact`, `SetErrorHandler`, and `SetAppendix`. 
What we are doing in this benchmark is make sure the fixed weight assumption is more than the actual benchmarked weight, which was the case after running the AWS benchmark.

We can add a new case to `FixedWeightBounds` to use our benchmarked weight for the xcmp notifications, but I don't think it's necessary for now.

**Comment by vstam1** [comment]
Could we add a test to our runtime that actually checks if these weights are lower then our hardcoded weights?

**Review by vstam1 — APPROVED** [review]

**Comment by JuaniRios** [comment]
### Merge activity

* **Jul 8, 8:35 AM EDT**: @JuaniRios started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Polimec/polimec-node/351).

**Pull request merged**
