### PR TITLE
👨🏻‍💻 Reorg extrinsics

### PR DESCRIPTION
**Pull request by JuaniRios**
## What?
Change the order, naming, and indexing of some extrinsics

## Why?
Easier readability, and less guessing what the next index will be for new extrinsics

### CODE REVIEW

**Comment by JuaniRios** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/345?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#345** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/345?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#341** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/341?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#344** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/344?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @JuaniRios and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by vstam1 — COMMENTED** [review]
I think it would be good to keep all the project transition (root) functions together for now. With the project simplifications we will probably move from automatic to semi automatic transitions, so the root function won't be necessary anymore. We will probably rename them and make them available for anyone to be called. However, we might change some protocol flow as well (merge auction rounds, merge community + remainder round and maybe remove decision logic) so we might have to do the reindexing all over again.

**Comment by lrazovic** [comment]
> However, we might change some protocol flow as well (merge auction rounds, merge community + remainder round and maybe remove decision logic) so we might have to do the reindexing all over again.

In order to minimize the number of times we do a re-index, isn't it better to do it once the protocol simplification has been done?

**Comment by vstam1** [comment]
Yeah think so as well!

**Comment by JuaniRios** [comment]
> > However, we might change some protocol flow as well (merge auction rounds, merge community + remainder round and maybe remove decision logic) so we might have to do the reindexing all over again.
> 
> In order to minimize the number of times we do a re-index, isn't it better to do it once the protocol simplification has been done? 

Right now there is no reason not to reindex. But that might change in the future. So I would rather reindex now since we know there are no side effects.

We already have the indexes all over the place

**Review by vstam1 — APPROVED** [review]
I don't like that we probably have to reindex twice, but I won't block the pr if you are convinced

**Review by lrazovic — APPROVED** [review]

**Comment by JuaniRios** [comment]
### Merge activity

* **Jul 8, 8:35 AM EDT**: @JuaniRios started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Polimec/polimec-node/345).

**Pull request merged**
