### PR TITLE
💻 Run new benchmarks

### PR DESCRIPTION
**Pull request by JuaniRios**
## What?
- Run the added benchmarks on AWS and put them on the pallet and runtime weight files
- hrmp benches ended up being lower than assumed XCM constant, so we're safe there.

## How?
- Created a new just file to benchmark only certain extrinsics called `benchmark-extrinsics`

## Anything Else?
- I saw that the only difference between the pallet and runtime benchmark configurations in our just-file are the flags 
```
--no-storage-info \
--no-median-slopes \
--no-min-squares \
```
And those ones only seem to be affecting the print to console and not the actual benchmarking, so I copy-pasted the generated weights to both the pallet and runtime files

### CODE REVIEW

**Comment by JuaniRios** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/352?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#352** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/352?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#351** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/351?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#346** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/346?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#345** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/345?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#341** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/341?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#344** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/344?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @JuaniRios and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by vstam1 — COMMENTED** [review]
Quickly skimmed the weights, and they look good. Only question I still have is around this do_handle_channel_* benchmarks. I'm not sure if it would work like this.

**Comment by JuaniRios** [comment]
@vstam1
>not sure if it would work like this. 

Could you elaborate more what you meant?

**Comment by vstam1** [comment]
Related to the question in the prev PR. Can continue 'discussion' there

**Review by vstam1 — APPROVED** [review]

**Comment by JuaniRios** [comment]
### Merge activity

* **Jul 8, 8:35 AM EDT**: @JuaniRios started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Polimec/polimec-node/352).

**Pull request merged**
